# Generated by Django 3.2.16 on 2023-01-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoiceanswer",
            name="answer",
            field=models.CharField(max_length=50),
        ),
    ]
