# Generated by Django 3.2.16 on 2023-01-23 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0002_alter_multiplechoiceanswer_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 1, 23, 14, 57, 56, 340487, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="tags",
            field=models.ManyToManyField(blank=True, to="evaluations.Tag"),
        ),
        migrations.AlterField(
            model_name="evaluationfreeformanswer",
            name="evaluation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freeform_answers",
                to="evaluations.evaluation",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationmultiplechoiceanswer",
            name="evaluation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multiple_choice_answers",
                to="evaluations.evaluation",
            ),
        ),
        migrations.AlterField(
            model_name="freeformquestion",
            name="question_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freeform_questions",
                to="evaluations.questionset",
            ),
        ),
        migrations.AlterField(
            model_name="multiplechoiceanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="evaluations.multiplechoicequestion",
            ),
        ),
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="question_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multiple_choice_questions",
                to="evaluations.questionset",
            ),
        ),
    ]
