# Generated by Django 3.2.16 on 2023-01-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0003_auto_20230123_0957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="evaluations.tagcategory",
            ),
        ),
    ]
