# Generated by Django 3.2.16 on 2023-01-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0005_auto_20230123_1034"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyQuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_id", models.IntegerField(unique=True)),
                (
                    "question_set",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.questionset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyMultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_id", models.IntegerField(unique=True)),
                (
                    "multiple_choice_question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.multiplechoicequestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyMultipleChoiceAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_id", models.IntegerField(unique=True)),
                (
                    "multiple_choice_answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.multiplechoiceanswer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyFreeformQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_id", models.IntegerField(unique=True)),
                (
                    "freeform_question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.freeformquestion",
                    ),
                ),
            ],
        ),
    ]
