# Generated by Django 3.2.16 on 2023-01-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "evaluations",
            "0006_legacyfreeformquestion_legacymultiplechoiceanswer_legacymultiplechoicequestion_legacyquestionset",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformquestion",
            name="required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="multiplechoicequestion",
            name="required",
            field=models.BooleanField(default=True),
        ),
    ]
