# Generated by Django 3.2.16 on 2023-01-23 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0008_reportcategorizer_reportcategorizertagcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "question_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.questionset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadConfigurationTagCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("split", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.tagcategory",
                    ),
                ),
                (
                    "upload_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.uploadconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["category__name"],
            },
        ),
    ]
