# Generated by Django 3.2.16 on 2023-02-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_uploadconfiguration_uploadconfigurationtagcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadconfigurationtagcategory',
            name='upload_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_categories', to='evaluations.uploadconfiguration'),
        ),
    ]
