# Generated by Django 3.2.16 on 2023-02-26 19:14

from django.db import migrations


def create_upload_id_tag(apps, schema_editor):
    TagCategory = apps.get_model("evaluations", "TagCategory")
    TagCategory.objects.create(
        name="Upload ID", system_managed=True, admin_filter_display_values=True
    )


def delete_upload_id_tag(apps, schema_editor):
    TagCategory = apps.get_model("evaluations", "TagCategory")
    TagCategory.objects.get(name="Upload ID").delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "evaluations",
            "0010_alter_uploadconfigurationtagcategory_upload_configuration",
        ),
    ]

    operations = [migrations.RunPython(create_upload_id_tag, delete_upload_id_tag)]
