# Generated by Django 3.2.16 on 2023-03-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_remove_tagcategory_admin_filter_display_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategory',
            name='admin_filter_breakout_values',
            field=models.BooleanField(default=False, help_text='Show this tag category as an admin evaluation filter'),
        ),
    ]
