# Generated by Django 3.2.13 on 2022-05-27 15:01

from django.db import migrations, models
from datetime import timedelta


def set_discard_after(apps, schema_editor):
    """Set the discard_after values"""

    del schema_editor

    OutgoingMessage = apps.get_model("stored_mail", "OutgoingMessage")
    unset = OutgoingMessage.objects.filter(discard_after__isnull=True)
    unset.update(discard_after=models.F('created_at') + timedelta(days=7))


class Migration(migrations.Migration):

    dependencies = [
        ('stored_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='discard_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(set_discard_after, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='outgoingmessage',
            name='discard_after',
            field=models.DateTimeField(),
        ),
    ]
