# Generated by Django 3.2.9 on 2021-11-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stored_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmessage',
            name='sent_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
