# Generated by Django 3.2.9 on 2021-11-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stored_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='reply_to_address',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='reply_to_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
