# Generated by Django 3.2.9 on 2021-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stored_mail', '0002_alter_outgoingmessage_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='last_send_attempt',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
