# Generated by Django 3.2.16 on 2022-10-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stored_mail", "0004_alter_outgoingmessage_discard_after"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="relatedaddress",
            unique_together={("address", "message", "field")},
        ),
    ]
