# Generated by Django 3.2.5 on 2021-07-25 22:38

from django.db import migrations, models
import django.db.models.deletion
import icons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to=icons.models.icon_original_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon', models.ImageField(upload_to=icons.models.icon_original_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icons.icon')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_icons', to='icons.page')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('page', 'icon')},
            },
        ),
        migrations.CreateModel(
            name='PageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icons.folder')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_folders', to='icons.page')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('page', 'folder')},
            },
        ),
        migrations.CreateModel(
            name='FolderIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_icons', to='icons.folder')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icons.icon')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('folder', 'icon')},
            },
        ),
        migrations.CreateModel(
            name='CrossLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5)),
                ('crosslink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icons.page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosslinks', to='icons.page')),
            ],
            options={
                'unique_together': {('page', 'crosslink')},
            },
        ),
    ]
