# Generated by Django 3.2.5 on 2021-07-26 00:24

from django.db import migrations
import icons.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(upload_to=icons.models.icon_original_upload_to),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(upload_to=icons.models.icon_original_upload_to),
        ),
    ]
