# Generated by Django 3.2.5 on 2021-07-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
