# Generated by Django 3.2.5 on 2021-07-20 22:03

from django.db import migrations, models
import django.db.models.deletion
import icons.models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0003_icon_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.ImageField(upload_to=icons.models.icon_original_upload_to),
        ),
        migrations.CreateModel(
            name='PageIconDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons.icon')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons.page')),
            ],
        ),
    ]
