# Generated by Django 3.2.5 on 2021-07-21 02:06

from django.db import migrations, models
import icons.models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0004_auto_20210720_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to=icons.models.icon_original_upload_to)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pageicondisplay',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='pageicondisplay',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
