# Generated by Django 3.2.5 on 2021-07-21 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0006_auto_20210721_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageitem',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icons.folder'),
        ),
        migrations.AlterField(
            model_name='pageitem',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icons.icon'),
        ),
    ]
