# Generated by Django 3.2.5 on 2021-07-24 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0007_auto_20210721_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PageIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icons.icon')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_icons', to='icons.page')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('page', 'icon')},
            },
        ),
        migrations.CreateModel(
            name='TextLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('crosslink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icons.page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_links', to='icons.page')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='icons',
            field=models.ManyToManyField(through='icons.FolderIcon', to='icons.Icon'),
        ),
        migrations.AlterField(
            model_name='foldericon',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_icons', to='icons.folder'),
        ),
        migrations.AlterField(
            model_name='foldericon',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icons.icon'),
        ),
        migrations.DeleteModel(
            name='PageItem',
        ),
        migrations.AddField(
            model_name='pagefolder',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icons.folder'),
        ),
        migrations.AddField(
            model_name='pagefolder',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_folders', to='icons.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='folders',
            field=models.ManyToManyField(through='icons.PageFolder', to='icons.Folder'),
        ),
        migrations.AddField(
            model_name='page',
            name='icons',
            field=models.ManyToManyField(through='icons.PageIcon', to='icons.Icon'),
        ),
        migrations.AlterUniqueTogether(
            name='pagefolder',
            unique_together={('page', 'folder')},
        ),
    ]
