# Generated by Django 3.2.5 on 2021-07-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0008_auto_20210724_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='icons',
        ),
        migrations.RemoveField(
            model_name='page',
            name='folders',
        ),
        migrations.RemoveField(
            model_name='page',
            name='icons',
        ),
    ]
