# Generated by Django 3.2.5 on 2021-07-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0009_auto_20210724_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlink',
            name='position',
            field=models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], default=None, max_length=5),
            preserve_default=False,
        ),
    ]
