# Generated by Django 3.2.5 on 2021-07-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0010_textlink_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textlink',
            name='position',
        ),
    ]
