# Generated by Django 3.2.5 on 2021-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0011_remove_textlink_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlink',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textlink',
            name='side',
            field=models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], default=None, max_length=5),
            preserve_default=False,
        ),
    ]
