# Generated by Django 3.2.5 on 2021-07-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0012_auto_20210725_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlink',
            name='title',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textlink',
            name='crosslink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icons.page'),
        ),
    ]
