# Generated by Django 3.2.5 on 2021-07-25 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0013_auto_20210725_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5)),
                ('crosslink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icons.page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_links', to='icons.page')),
            ],
            options={
                'unique_together': {('page', 'crosslink')},
            },
        ),
        migrations.DeleteModel(
            name='TextLink',
        ),
    ]
