[project]
name = "rectory-apps"
version = "0.0.0"
description = ""
authors = [{ name = "Adam Peacock", email = "adam@thepeacock.net" }]
requires-python = "<3.13,>=3.12"
readme = "README.md"
license = { text = "MIT" }
dependencies = [
    "django~=5.2.17",
    "django-environ~=0.14.0",
    "django-admin-sortable2~=2.3.1",
    "whitenoise~=6.12.0",
    "gunicorn~=26.1.0",
    "django-safemigrate~=6.0",
    "django-bootstrap4~=26.1",
    "google-auth~=2.56.3",
    "requests~=2.34.2",
    "reportlab~=5.0.1",
    "django-anymail[mailgun]~=15.1",
    "django-lb-health-check<2.0,>=1.0",
    "django-quick-jobs>=0.4.0",
    "htmlBuilder<2.0.0,>=1.0.0",
    "structlog>=26.1.0",
    "django-solo~=2.5.1",
    "django-structlog~=10.1.0",
    "humanize~=4.16.0",
    "django-simple-history~=3.13.0",
    "pydantic~=2.13.4",
    "django-hijack~=3.7.8",
    "frozendict~=2.4.7",
    "django-node-assets<1.0.0,>=0.9.16",
    "premailer<4.0.0,>=3.10.0",
    "django-braces<2.0.0,>=1.17.0",
    "psycopg>=3.3.4",
    "django-bootstrap-breadcrumbs @ git+https://github.com/Hovercross/bootstrap-breadcrumbs.git",
]

[tool.django-stubs]
django_settings_module = "core.settings"


[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "django-debug-toolbar>=6.0.0",
    "django-stubs>=5.2.2",
    "django-stubs-ext>=5.2.2",
    "djlint>=1.36.4",
    "ipython>=9.5.0",
    "mypy>=1.17.1",
    "pytest>=8.4.1",
    "pytest-django>=4.11.1",
    "rope>=1.14.0",
    "types-requests>=2.32.4.20250809",
]
