[tool.poetry]
name = "rectory-apps"
version = "0.0.0"
description = ""
authors = ["Adam Peacock <adam@thepeacock.net>"]

[tool.poetry.dependencies]
python = "^3.10"
django = "~=3.2"
django-environ = "*"
django-admin-sortable2 = "*"
pillow = "*"
psycopg2 = "*"
whitenoise = "*"
uvicorn = "*"
gunicorn = "*"
django-safemigrate = "*"
django-bootstrap4 = "*"
google-auth = "*"
requests = "*"
django-health-check = "*"
reportlab = "*"
django-bootstrap-breadcrumbs = "*"
djangorestframework = "*"
markdown = "*"
django-filter = "*"
django-storages = "*"
boto3 = "*"
django-versatileimagefield = "*"
django-solo = "*"
logzio-python-handler = "*"
django-ipware = "*"
django-anymail = {extras = ["mailgun"], version = "*"}
django-lb-health-check = "^1.0"
django-quick-jobs = "^0.2.0"

[tool.poetry.dev-dependencies]
autopep8 = "*"
rope = "*"
pylint = "*"
pytest = "*"
pytest-django = "*"
django-debug-toolbar = "*"
ipython = "*"
pylint-django = "*"
pyyaml = "*"
uritemplate = "*"
mypy = "^0.950"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
