# Generated by Django 3.2.7 on 2021-09-06 21:10

from django.db import migrations, models
import django.db.models.deletion
import sis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('course_name_short', models.CharField(blank=True, max_length=255)),
                ('course_name_transcript', models.CharField(blank=True, max_length=255)),
                ('division', models.CharField(blank=True, max_length=2)),
                ('grade_level', models.CharField(blank=True, max_length=2)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('course_type', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetentionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=63, unique=True)),
                ('process', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetentionOffense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentence_insert', models.TextField(blank=True)),
                ('send_mail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2, unique=True)),
                ('description', models.CharField(blank=True, max_length=63)),
                ('school', models.CharField(blank=True, choices=[('', '--'), ('elementary', 'Elementary School'), ('middle', 'Middle School'), ('high', 'High School')], default='', max_length=10)),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(max_length=20)),
                ('parent_id', models.CharField(max_length=2)),
                ('first_name', models.CharField(blank=True, max_length=63)),
                ('last_name', models.CharField(blank=True, max_length=63)),
                ('middle_name', models.CharField(blank=True, max_length=63)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone_home', models.CharField(blank=True, max_length=63)),
                ('phone_work', models.CharField(blank=True, max_length=63)),
                ('phone_cell', models.CharField(blank=True, max_length=63)),
                ('address', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('family_id', 'parent_id')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csn', models.CharField(max_length=255)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=7, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, default='', max_length=1)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=5, unique=True)),
                ('unique_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('prefix', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_reg_id', models.CharField(max_length=20, unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentParentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.student')),
            ],
            options={
                'unique_together': {('student', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, through='sis.StudentParentRelation', to='sis.Parent'),
        ),
        migrations.AddField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(through='sis.StudentRegistration', to='sis.Student'),
        ),
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.teacher'),
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_name', models.CharField(max_length=63, unique=True)),
                ('building', models.CharField(blank=True, max_length=20)),
                ('wing', models.CharField(blank=True, max_length=20)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('heads', models.ManyToManyField(blank=True, limit_choices_to={'active': True}, related_name='_sis_dorm_heads_+', to='sis.Teacher', verbose_name='dorm parents')),
            ],
            options={
                'ordering': ['building', 'wing', 'level', 'dorm_name'],
            },
        ),
        migrations.CreateModel(
            name='Detention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detention_id', models.CharField(max_length=63, unique=True)),
                ('comments', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.academicyear')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='detentions', to='sis.detentioncode')),
                ('offense', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='detentions', to='sis.detentionoffense')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sis.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.ForeignKey(default=sis.models.latest_academic_year, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sis.academicyear')),
            ],
            options={
                'verbose_name': 'SIS Configuration',
            },
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('csn', 'academic_year')},
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarder', models.BooleanField()),
                ('division', models.CharField(max_length=2)),
                ('section', models.CharField(blank=True, max_length=1)),
                ('status_enrollment', models.CharField(blank=True, max_length=20)),
                ('status_attending', models.CharField(blank=True, max_length=20)),
                ('enrolled_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.academicyear')),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.teacher')),
                ('dorm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.dorm')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sis.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.student')),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name', 'academic_year__year'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
