# Generated by Django 3.2.7 on 2021-09-06 21:13

from django.db import migrations


def create_groups(apps, schema_editor):
    """Create the SIS Syncer group"""

    del schema_editor

    # pylint: disable=invalid-name
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    sis_full_permission = Permission.objects.filter(content_type__app_label='sis')

    sis_syncers, _ = Group.objects.get_or_create(name="SIS Syncers")
    sis_syncers.permissions.add(*sis_full_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, migrations.RunPython.noop)
    ]
