# Generated by Django 3.2.7 on 2021-09-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='current',
        ),
    ]
