# Generated by Django 3.2.7 on 2021-09-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0002_remove_academicyear_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current',
        ),
    ]
