# Generated by Django 3.2.7 on 2021-09-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0004_auto_20210906_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentparentrelation',
            name='family_id_key',
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('family_id', 'parent_id')},
        ),
        migrations.RemoveField(
            model_name='parent',
            name='full_id',
        ),
    ]
