# Generated by Django 3.2.7 on 2021-09-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_auto_20210906_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_cell',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_home',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_work',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
