# Generated by Django 3.2.7 on 2021-09-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_alter_grade_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dorm',
            options={'ordering': ['building', 'wing', 'level', 'dorm_name']},
        ),
        migrations.AlterField(
            model_name='dorm',
            name='building',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
