# Generated by Django 3.2.7 on 2021-09-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0008_auto_20210906_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='dorm_name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
