# Generated by Django 3.2.7 on 2021-09-06 18:21

from django.db import migrations, models
import django.db.models.deletion
import sis.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0009_alter_dorm_dorm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='current_year',
            field=models.ForeignKey(default=sis.models.latest_academic_year, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sis.academicyear'),
        ),
    ]
