# Generated by Django 3.2.7 on 2021-09-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0010_alter_config_current_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetentionOffense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detention_id', models.CharField(max_length=63, unique=True)),
                ('comments', models.TextField()),
                ('date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.academicyear')),
                ('offense', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sis.detentionoffense')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sis.teacher')),
            ],
        ),
    ]
