# Generated by Django 3.2.7 on 2021-09-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0012_alter_detentionoffense_offense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detentionoffense',
            name='offense',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
