# Generated by Django 3.2.7 on 2021-09-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0013_alter_detentionoffense_offense'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetentionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=63, unique=True)),
                ('process', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='detention',
            name='offense',
        ),
        migrations.AlterField(
            model_name='detention',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='detentionoffense',
            name='offense',
            field=models.TextField(unique=True),
        ),
        migrations.AddField(
            model_name='detention',
            name='code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sis.detentioncode'),
            preserve_default=False,
        ),
    ]
