# Generated by Django 3.2.7 on 2021-09-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0014_auto_20210906_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='detention',
            name='offense',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sis.detentionoffense'),
            preserve_default=False,
        ),
    ]
