# Generated by Django 3.2.7 on 2021-09-06 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0015_detention_offense'),
    ]

    operations = [
        migrations.AddField(
            model_name='detentionoffense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detentionoffense',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detentionoffense',
            name='sentence_insert',
            field=models.TextField(blank=True),
        ),
    ]
