# Generated by Django 3.2.15 on 2022-09-20 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enrichment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="signup",
            options={
                "permissions": (
                    (
                        "edit_past_lockout",
                        "Can edit enrichment signups past the lockout time",
                    ),
                    (
                        "ignore_admin_locked",
                        "Can edit enrichment signups regardless of admin lock",
                    ),
                    (
                        "use_admin_only_options",
                        "Can assign students to admin only options",
                    ),
                    ("assign_all_advisees", "Can assign any advisees"),
                )
            },
        ),
        migrations.AddField(
            model_name="locationoverride",
            name="location",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="locationoverride",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_overrides",
                to="enrichment.option",
            ),
        ),
    ]
