# Generated by Django 3.2.15 on 2022-09-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrichment", "0002_auto_20220920_1728"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slot",
            options={"ordering": ["date", "title"]},
        ),
        migrations.AlterField(
            model_name="historicalslot",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="slot",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
