# Generated by Django 3.2.15 on 2022-09-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrichment", "0004_auto_20220921_1208"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="What weekday this applies to",
                        unique=True,
                    ),
                ),
                (
                    "days_before",
                    models.PositiveSmallIntegerField(
                        help_text="How many days before the slot date the lockout should be effective"
                    ),
                ),
                (
                    "time",
                    models.TimeField(help_text="When the slot should be locked out"),
                ),
            ],
        ),
    ]
