# Generated by Django 3.2.15 on 2022-09-21 21:49

from django.db import migrations
from django.contrib.auth.management import create_permissions


def migrate_permissions(apps, schema_editor):
    """Create the permissions, especially for testing"""

    del schema_editor

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def add_permission(apps, schema_editor):
    migrate_permissions(apps, schema_editor)

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    required_permissions = [
        "change_signup",
    ]

    group = Group.objects.get(name="Enrichment Managers")

    permission = Permission.objects.get(
        content_type__app_label="enrichment",
        codename="change_signup",
    )

    group.permissions.add(permission)


def remove_permission(apps, schema_editor):
    migrate_permissions(apps, schema_editor)

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    required_permissions = [
        "change_signup",
    ]

    group = Group.objects.get(name="Enrichment Managers")

    permission = Permission.objects.get(
        content_type__app_label="enrichment",
        codename="change_signup",
    )

    group.permissions.remove(permission)


class Migration(migrations.Migration):

    dependencies = [
        ("enrichment", "0005_editconfig"),
    ]

    operations = [migrations.RunPython(add_permission, remove_permission)]
