# Generated by Django 3.2.15 on 2022-10-14 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("enrichment", "0008_emailconfig_historicalemailconfig_relatedaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfig",
            name="report",
            field=models.CharField(
                choices=[
                    ("unassigned_advisor", "Unassigned advisees to advisors"),
                    ("unassigned_admin", "Unassigned advisees to admins"),
                    ("advisor_signups", "Advisee locations to advisors"),
                    ("advisee_signups", "Advisee locations to advisees"),
                    ("facilitator_signups", "Advisee locations to facilitators"),
                    ("all_signups", "Full signup report"),
                ],
                max_length=19,
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("America/New_York", "America/New_York"),
                    ("America/Chicago", "America/Chicago"),
                    ("America/Denver", "America/Denver"),
                    ("America/Phoenix", "America/Phoenix"),
                    ("America/Los_Angeles", "America/Los_Angeles"),
                    ("America/Anchorage", "America/Anchorage"),
                    ("America/Adak", "America/Adak"),
                    ("Pacific/Honolulu", "Pacific/Honolulu"),
                    ("UTC", "UTC"),
                ],
                default=django.utils.timezone.get_current_timezone_name,
                max_length=19,
            ),
        ),
        migrations.AlterField(
            model_name="historicalemailconfig",
            name="report",
            field=models.CharField(
                choices=[
                    ("unassigned_advisor", "Unassigned advisees to advisors"),
                    ("unassigned_admin", "Unassigned advisees to admins"),
                    ("advisor_signups", "Advisee locations to advisors"),
                    ("advisee_signups", "Advisee locations to advisees"),
                    ("facilitator_signups", "Advisee locations to facilitators"),
                    ("all_signups", "Full signup report"),
                ],
                max_length=19,
            ),
        ),
        migrations.AlterField(
            model_name="historicalemailconfig",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("America/New_York", "America/New_York"),
                    ("America/Chicago", "America/Chicago"),
                    ("America/Denver", "America/Denver"),
                    ("America/Phoenix", "America/Phoenix"),
                    ("America/Los_Angeles", "America/Los_Angeles"),
                    ("America/Anchorage", "America/Anchorage"),
                    ("America/Adak", "America/Adak"),
                    ("Pacific/Honolulu", "Pacific/Honolulu"),
                    ("UTC", "UTC"),
                ],
                default=django.utils.timezone.get_current_timezone_name,
                max_length=19,
            ),
        ),
    ]
