# Generated by Django 3.2.15 on 2022-09-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "blackbaud",
            "0002_advisorycourse_advisoryschool_historicaladvisorycourse_historicaladvisoryschool",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenrollment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_enrollments",
                to="blackbaud.class",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="enrollments",
                to="blackbaud.student",
            ),
        ),
        migrations.AlterField(
            model_name="teacherenrollment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="teacher_enrollments",
                to="blackbaud.class",
            ),
        ),
        migrations.AlterField(
            model_name="teacherenrollment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="enrollments",
                to="blackbaud.teacher",
            ),
        ),
    ]
