# Generated by Django 3.2.5 on 2021-07-16 01:07

from django.db import migrations


def create_groups(apps, schema_editor):
    """Create the appropriate groups"""

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    full_calendar = Permission.objects.filter(content_type__app_label='calendar_generator')
    calendar_view = Permission.objects.filter(
        content_type__app_label='calendar_generator', content_type__model='calendar', codename='view_calendar')

    calendar_viewer = Group.objects.create(name="Calendar viewers")
    calendar_viewer.permissions.add(*calendar_view)

    calendar_manager = Group.objects.create(name="Calendar managers")
    calendar_manager.permissions.add(*full_calendar)


def delete_groups(apps, schema_editor):
    """Remove the appropriate groups"""

    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name="Calendar viewers").delete()
    Group.objects.filter(name="Calendar managers").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_generator', '0002_alter_day_position'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups)
    ]
