# Generated by Django 3.2.5 on 2021-07-16 02:16

from django.db import migrations


def create_groups(apps, schema_editor):
    """Create the appropriate groups"""

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    calendar_full_permission = Permission.objects.filter(content_type__app_label='calendar_generator')
    calendar_view_permission = Permission.objects.get(content_type__app_label='calendar_generator',
                                                      content_type__model='calendar',
                                                      codename='view_calendar')

    admin_login_permission = Permission.objects.get(content_type__app_label='accounts',
                                                    content_type__model='user',
                                                    codename='admin_login')

    calendar_viewer, _ = Group.objects.get_or_create(name="Calendar viewers")
    calendar_viewer.permissions.add(calendar_view_permission)

    calendar_manager, _ = Group.objects.get_or_create(name="Calendar managers")
    calendar_manager.permissions.add(*calendar_full_permission)
    calendar_manager.permissions.add(admin_login_permission)


def delete_groups(apps, schema_editor):
    """Remove the appropriate groups"""

    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name="Calendar viewers").delete()
    Group.objects.filter(name="Calendar managers").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_generator', '0003_auto_20210716_0216'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups)
    ]
